name: Vulnerable Docker Build and Push

on: push

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CI_CD_TOKEN }}
    
    - id: octoscan
      name: Run octoscan
      uses: synacktiv/action-octoscan@v1

    - name: Upload SARIF file to GitHub
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: "${{steps.octoscan.outputs.sarif_output}}"
        category: octoscan

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest