name: Docker Build and Push

on:
  push:
    branches: [ master, main ]

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_USERNAME: badactors
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@latest
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/hello-world-app:latest .
        docker push ${{ env.DOCKER_USERNAME }}/hello-world-app:latest