name: Docker Build and Push

on:
  push:
    branches: [ master, main, trufflehog ]

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: 'recursive'
        token: ${{ secrets.CI_CD_TOKEN }}
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest .


    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: docker --image docker://${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest --results=verified,unknown


    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest